### 六，错误处理&资源管理

##### 一）defer调用

- 在函数处理完成调用
- 参数在defer语句时计算
- defer定义一个栈，先进后出

```go
func tryDefer() {
  defer fmt.Println(1)
  defer fmt.Println(2)
  fmt.Println(3)
  
  panic(err)
}
// 3 panic: err 2 1
// defer定义相当于一个栈，先进后出
```

```go
// 参数在defer语句时计算
func deferDemo() {
	for i := 0; i < 100; i++ {
		defer fmt.Println(i)
		if i == 10 {
			panic("err")
		}
	}
}
// 4
// 3
// 2
// 1
// 0
```

```go
// 文件操作
func writeFile(filename string) {
	file, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	for i := 0; i < 20; i++ {
		_, _ = fmt.Fprintln(writer, i)
	}
}
```